version: 0.1
phases:
  pre_build:
    commands:
      - curl -sL https://deb.nodesource.com/setup_6.x | bash -
      - apt-get install -y nodejs jq
      - $(aws ecr get-login --region us-west-2)
  build:
    commands:
      - chmod a+x ./mongodb/codebuild-docker-build.sh
      - bash cd mongodb && ./codebuild-docker-build.sh
      - chmod a+x ./lrs/codebuild-docker-build.sh
      - bash cd lrs && ./codebuild-docker-build.sh
      # - chmod a+x ./events/codebuild-docker-build.sh
      # - bash ./events/codebuild-docker-build.sh
artifacts:
  files:
    - ./**/*